@startuml {

    class SensorSimulator {
        - Random random
        + SensorService sensorService
        + simulateSensor(Sensor sensor)
    }

    SensorSimulator --> SensorService : <<Autowired>>
    SensorSimulator --> Sensor : simulateSensor(Sensor sensor)
}

@enduml
